import React from "react";
import {
  FaCloud,
  FaCrown,
  FaHandsHelping,
  FaSuperpowers,
} from "react-icons/fa";
import { GoGistSecret } from "react-icons/go";

const HeroSection = () => {
  return (
    <section className="page-root z-10 snap-start bg-gradient-to-tr from-[#0d0511] to-[#090e14] text-slate-50">
      <h1 className="z-10 bg-gradient-to-r from-amber-400 via-green-400 to-blue-400 bg-clip-text text-8xl font-bold text-transparent">
        Passwords Are Dead
      </h1>
      <h2 className="z-10 text-3xl font-medium text-slate-500">
        Still stuck in the 90s?{" "}
        <span className="font-semibold text-slate-300">
          Pashword is the Future
        </span>{" "}
      </h2>
      <div>
        <img src="/with-without-pashword.svg" className="mx-auto" />
      </div>
      <div className="z-10 mt-10 flex flex-col space-y-5 text-center">
        <h3 className="text-xl font-semibold text-slate-300">Why?</h3>
        <div className="container flex flex-wrap justify-center gap-5 ">
          <div className="card-container">
            <FaCrown className="text-lg" />
            <h4 className="card-heading">One Pass to Rule them all</h4>
            <p className="card-content">
              Gone are the days of remembering multiple passwords. Pashword
              generates your passwords for you, for your websites and usernames.
            </p>
          </div>
          <div className="card-container">
            <FaSuperpowers className="text-lg" />
            <h4 className="card-heading">Pass of Steel</h4>
            <p className="card-content">
              Pashword is cryptographically secure. A password generated by
              Pashword can take thousands of trillions of years to break, now
              that, is strong.
            </p>
          </div>
          <div className="card-container">
            <GoGistSecret className="text-lg" />
            <h4 className="card-heading">Your special secret</h4>
            <p className="card-content">
              Your pashword belongs only to you and no one else. Only you can
              generate a pashword for your accounts.
            </p>
          </div>
          <div className="card-container">
            <FaHandsHelping className="text-lg" />
            <h4 className="card-heading">Open Source</h4>
            <p className="card-content">
              Pashword is 100% Free and Open Source. It is transparent,
              anonymous and privacy respecting by default.
            </p>
          </div>
          <div className="card-container">
            <FaCloud className="text-lg" />
            <h4 className="card-heading">Works without Internet</h4>
            <p className="card-content">
              Pashword works without internet. All your pashwords are generated
              locally on your computer and no connection is made to outside
              servers. Everything stays on your device, secure.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
